science = Category.create(name:"国語")
science.children.create([{name:"漢字"}, {name:"古典"}, {name:"漢文"}, {name:"現代文"}])
science = Category.create(name:"数学")
science.children.create([{name:"ⅠA"}, {name:"ⅡB"}, {name:"Ⅲ"}])
science = Category.create(name:"英語")
science.children.create([{name:"単語"}, {name:"熟語"}, {name:"長文"}])
science = Category.create(name:"理科")
science.children.create([{name:"物理"}, {name:"化学"}, {name:"生物"}, {name:"地学"}])
social = Category.create(name:"社会")
social.children.create([{name:"日本史"}, {name:"世界史"}, {name:"地理"}, {name:"現代社会"}])
social = Category.create(name:"雑学")
social.children.create([{name:"常識"}, {name:"博識"}, {name:"知っていればかっこいい"}, {name:"知ってそうで知らない"}])